complete -c toi -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c toi -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c toi -n "__fish_use_subcommand" -f -a "run" -d 'Run toidb in the background'
complete -c toi -n "__fish_use_subcommand" -f -a "connect" -d 'Connect to a toidb instance'
complete -c toi -n "__fish_use_subcommand" -f -a "generate-completion" -d 'Generate toi completions for the specified shell'
complete -c toi -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c toi -n "__fish_seen_subcommand_from run" -s h -l help -d 'Print help information'
complete -c toi -n "__fish_seen_subcommand_from connect" -s h -l help -d 'Print help information'
complete -c toi -n "__fish_seen_subcommand_from generate-completion" -s h -l help -d 'Print help information'
complete -c toi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from connect; and not __fish_seen_subcommand_from generate-completion; and not __fish_seen_subcommand_from help" -f -a "run" -d 'Run toidb in the background'
complete -c toi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from connect; and not __fish_seen_subcommand_from generate-completion; and not __fish_seen_subcommand_from help" -f -a "connect" -d 'Connect to a toidb instance'
complete -c toi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from connect; and not __fish_seen_subcommand_from generate-completion; and not __fish_seen_subcommand_from help" -f -a "generate-completion" -d 'Generate toi completions for the specified shell'
complete -c toi -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from run; and not __fish_seen_subcommand_from connect; and not __fish_seen_subcommand_from generate-completion; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
