[package]
name = "fm"
version = "0.1.0"
edition = "2021"
rust-version = "1.64.0"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
directories = "4.0.1"
fs_extra = "1.2.0"
path-absolutize = "3.0.13"
